### PR TITLE
feat: Use SharedPreferences for android

### PR DESCRIPTION
**Pull request by demetris-manikas**
Basic implementation is finished. 
Please review code while I take care of migration and tests.

### CODE REVIEW

**Comment by demetris-manikas** [comment]
Migration to native AES ported to use SharedPreferences
Migration of values from localstorage to Shared preferences still pending.

**Comment by ggozad** [comment]
I haven't had the time to look at it but will certainly do during the week.
With regards to migration:

Please drop the migration to native altogether. This was a few versions ago. Sorry for telling too late, but we really don't need to support that anymore and it will probably remove some of the android mess.

**Comment by demetris-manikas** [comment]
PR is now ready.
I had already implemented the migration so it is still here.
Dropping the migration means dropping support for API 19 in favor of 21.
I agree that the code does not look nice anymore. 
I suggest we keep a branch of the current implementation and drop sjcl and migrations in a clean major release change that would support API 21 and above.
Cheers

**Comment by ggozad** [comment]
This looks good from a first glance. Will review thoroughly and merge asap.

**Comment by ggozad** [comment]
Works well, thank you!

The migration is correctly performed in the constructor after a successful ``init()``.
When the migration is performed though the first time the success() has been already called. Since the migration is not yet complete apps will unsuccessfully try to get a key.
I see you have added a ``success`` parameter to the ``_migrate_to_native_storage`` but it's not passed. Could you please fix that?

**Comment by demetris-manikas** [comment]
I reread the code and I believe it is fine.  success is only called only after both migrations have completed. Are you looking at the latest version of the code? I force push on a single commit.
Have you verified that the error is real or just read the code?
Please add comments about code at the code section so that it is more clear what you mean.
Thanks.

**Comment by ggozad** [comment]
I still failed the first time on the Crypho app to initialize properly, but it seems to work ever after. Merged.

**Pull request merged**
