### PR TITLE
Configurable ICloud Synchronization 

### PR DESCRIPTION
**Pull request by kidtrunk**
ICloud Synchronization is configurable on IOS.
If the plug-in don't receive the ICloud Sync Parameter, the plug-in keeps is default behavior

### CODE REVIEW

**Comment by ggozad** [comment]
Thanks for this, had a quick look, here are some questions:
Wouldn't it be better to pass a sync option when initialising the secure storage? Why would you want to it on ``set``?
Could you please add some documentation detailing how to use it?
Is it possible to test-cover it?
The diff on github shows you replaced some spaces with tabs... Let's stick with spaces only please.

**Comment by jvjvjv** [comment]
I agree that sync option should be part of init, not part of ```.set()```. We as the app developer would conceivably only be telling the plugin, ```"Do not sync with iCloud"``` only once. There is absolutely no need for the redundancy.

**Comment by demetris-manikas** [comment]
I guess the reason to define it on every set is that one might want to syncronize some values while others not.
In case we want a global setting I have to propose the following.
In the android part of cordova the CordovaPlugin class contains a preferences object so that the programmer can read the preferences set in config.xml. I guess there is something similar in the ios class as well. This way only a <preference/> under the ios section of the config.xml would do the job.

**Comment by demetris-manikas** [comment]
There it is 
https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/Public/NSDictionary%2BCordovaPreferences.h
Can someone do the job. Seems quite straightforward but I have no ios experience...

**Comment by demetris-manikas** [comment]
KeychainAccessibility is the option controlling whether iCloud backups are performed so I guess this PR may be dropped.

**Pull request closed without merging**
