### PR TITLE
Fixed: app crashes on iOS7

### PR DESCRIPTION
**Pull request by embedded-spirit**

### CODE REVIEW

**Comment by ggozad** [comment]
Sorry this fell under the bridge and I forgot about it. Is there any way to test it?

**Comment by embedded-spirit** [comment]
You can download and install Xcode 6 into a separate folder, run xcode-select --switch <Xcode6 folder>/Contents/Developer, build a sample Cordova app with the plugin and then use iOS7 simulator to test it.

**Comment by ggozad** [comment]
Excellent, would you mind documenting this in the README, i.e. what constants can be used when?

**Comment by ggozad** [comment]
Also please update the CHANGELOG with your github id. And happy new year!

**Comment by embedded-spirit** [comment]
Happy new year! README and CHANGELOG have been updated.

**Pull request merged**
