### PR TITLE
Add setting failOnDeviceInsecure to prevent OS warning

### PR DESCRIPTION
**Pull request by jdart**
I borrowed some of the language from pr #31.

I'm not sure what to make of `callbackContext.success(SUPPORTS_NATIVE_AES);` in the init action. Maybe I should call error instead of success?

### CODE REVIEW

**Comment by ggozad** [comment]
Hey,
Thanks for this. Yes, you should indeed call error with an exception as well as log it.
I am wondering if there is a better way to go about this. Should perhaps the isPinSet be exposed to the js bridge so that a check can be done beforehand? I am guessing this is redundant if the init fails, but open to suggestions.

Tests would be nice :)

**Comment by demetris-manikas** [comment]
Hi all. Looks to me that the added functionality belongs in another plugin. Anyway I suggest as @ggozad proposes that a isDeviceSecure method be added to the SecureStorage prototype (instead of isPinSet which is a bit misleading since all other device locking options are ignored) to be called independently.    

@jdart please take a look at the KeyguardManager.isDeviceSecure introduced in API 23 and see if it would make more sense to use when available. Thanks for contributing.

**Comment by ggozad** [comment]
I am wondering actually if it would be better to completely remove the warning and fail in the init() directly. The warning is confusing to the end-user, we are probably better off asking app developers to inform the user about what actions he needs to take rather than impose default messages.

**Comment by demetris-manikas** [comment]
Fine by me as long as it is optional. failOnDeviceInsecure would be my choice.

**Comment by ggozad** [comment]
@demetris-manikas why optional? Why not just fail and let the app developer inform the user and possibly retry?

**Comment by demetris-manikas** [comment]
Just because somebody might use the default and does not want to change current behaviour. Not a big matter anyway. Your ball.

**Comment by jdart** [comment]
I have updated the code based on your feedback. Regarding tests, I'm thinking that unless I mock the cordova.plugins.SecureStorage constructor entirely that I won't be able to detect that the device is secure or not, and so I won't be able to determine which handler should fire. Any advice on how to test?

**Comment by ggozad** [comment]
I don't want to add more complications but I think we can do better. I would like to avoid having options and rather make sane defaults.
What if:

On init we check and if the device is not secure we fail directly (no setting to fail or not).
In addition, ``unlockCredentials`` is renamed which brings up the dialog prompting the user to change the lock settings, is renamed to ``secureDevice``.

This way, the app developer has the opportunity to explain to the user why he needs them to change their lock pattern (something which the default android fails to do) what the fuck is the credential storage etc. Then the developer can decide (perhaps asking the user) if they want to call ``secureDevice`` and allow the user to change his settings.

Looking forward to your thoughts

**Comment by ggozad** [comment]
Also since ``isDeviceSecure`` is API level 23 it should only be used if available falling back to ``isKeyguardSecure``.

**Comment by ggozad** [comment]
With regards to tests, I realize this is hard to test automatically and having very little to do with android I have not much to offer in advice. Please test manually at least.

**Comment by ggozad** [comment]
I'm done with the code work I think, see pr/39 branch.

**Comment by jdart** [comment]
@ggozad Your work looks good to me, I'll do some manual testing.

**Comment by jdart** [comment]
Manual testing looks good on the api-23 try/catch, ss.secureDevice works as expected, and the error handler is firing as expected in init. Looks good to me. The tests suite I'm not having any luck with running at all. Still trying to figure that out.

**Comment by jdart** [comment]
@ggozad To run the tests, you install the cordova-plugin-test-framework plugin, make a build, then in your dev tools you do something like "window.location = '.../cdvtests/index.html'?"

**Comment by ggozad** [comment]
Oh I should add a section about the tests in the README. In the meantime, can you adapt from the instructions at https://github.com/Crypho/cordova-plugin-scrypt ?

**Comment by jdart** [comment]
I found that I needed to add <js-module src="tests/tests.js" name="tests"></js-module> to plugin.xml and re-add the platform - they're all passing for android.

**Comment by ggozad** [comment]
Added instructions for testing in the README. Could you let me know if I missed something?

**Comment by ggozad** [comment]
Let's take it to #42

**Pull request closed without merging**
