### PR TITLE
feat: use native AES on android

### PR DESCRIPTION
**Pull request by demetris-manikas**
NOTICE: This implementation is not compatible with the current one.

### CODE REVIEW

**Comment by ggozad** [comment]
Would be nice to have it backwards compatible. CCM mode is used in sjcl.

**Comment by demetris-manikas** [comment]
I tried decrypting the sjcl created ciphers to no avail. I faced the same problem as described in 
http://stackoverflow.com/questions/36461881/decrypting-aes-256-ccm-with-16byte-initial-vector-encrypted-by-sjcl
Solution given was to tag the natively produced payloads and use the sjcl decryption mechanism when the payload is not tagged as native. 
The only problem that remains is testability of the old implementation?
Any ideas are welcome.
Cheers

**Comment by yyfearth** [comment]
@demetris-manikas on the stackoverflow discussion, have you tried the suggested solution that slicing the nonce?
If it works, then we do not need to include the jscl at all.

**Comment by demetris-manikas** [comment]
I did give it a try without success. I 'll try a bit more. 
@yyfearth Can you give it a try as well? If you need any help on setting up a test project just tell me.

**Comment by demetris-manikas** [comment]
After a bit more investigation I came to the conclusion that the task is very difficult. The sjcl implementation works with a 4 word iv while the java one with a 3 word one. Since the iv is used to 
compute the mac there should be no way of deciphering an sjcl created cipher text with bouncycastle. 
@ggozad What is your opinion on the matter? 
I would also appreciate your opinions on the following.
1) The code could be arranged so as to set a natively created ciphertext whenever a non native ciphertext is requested. This way the use of native implementation would be used without any effort on behalf of the developer.
2) For the sake of safety should there be an initialization parameter as to only use sjcl implementation?

**Comment by ggozad** [comment]
I am guessing there must be a way to go back and forth between the two, but I do not have time to do this myself.

Perhaps the following would be adequate:
1) Provide a migration function, that decrypts with sjcl and re-encrypts with bouncycastle.
2) On decrypt, try first bouncycastle, if that fails try sjcl. If sjcl succeeds re-encrypt with bouncycastle.

I am ok keeping both for a few versions as long as the above 2 are in. Eventually we can phase off sjcl altogether. We cannot phase it off immediately.

**Comment by demetris-manikas** [comment]
Migration function called on init. 
Tests added.
Your ball.
Cheers

**Comment by ggozad** [comment]
Sorry to be so slow, stumped with work atm. Will try to review soon-ish :)

**Comment by yyfearth** [comment]
Any progress on this?

**Comment by ggozad** [comment]
I still haven't had the time to properly review this. @yyfearth perhaps you can help?
From a quick look:

What is the AES mode used? It's mentioned CCM/NoPadding but then GCM is used.
How is padding handled?
There are also some confusing DSA references. Can you clarify/clean up?

**Comment by yyfearth** [comment]
@ggozad Sorry for I cannot help you too much, since recently I'm also very busy for works.
But I will try the native AES part see it works when the conflicts been solved.
Since my app is a brand new app, I do not need to worry about migration that much.

**Comment by demetris-manikas** [comment]
No conflicts and cleaned up. 
@yyfearth Let me know how it works out for you.

**Comment by ggozad** [comment]
Great, I am going to be away for a few days, but this probably will give me enough time to review properly :)

**Comment by ggozad** [comment]
Thank you @demetris-manikas this looks great. Good to merge here are some final remarks:
1) Add a test for migration to native. If possible document the migration on the README.
2) On the SecureStorage constructor let's omit the ``_use_sjcl`` flag and use an ``options`` dict instead, with ``{native: true}`` as default values. This allows more options to be added later, without breaking the constructor.
3) If possible it would be nice if the commits where you add/remove sjcl.js were squashed since they just add noise.

I am otherwise very happy with the implementation. Perhaps we should set a milestone where the sjcl would be removed and document it in the README, let me know what you think.

**Comment by demetris-manikas** [comment]
@ggozad 

> Add a test for migration to native.

I have added tests for the migration. You may have missed them. The two last tests set a value with native:false and get it back using native:true (the default). (in the meantime the migration has occurred). If you think that this is not enough I am open to suggestions.

>If possible document the migration on the README

Since migration is completely transparent to the user I don't see any reason to document it.
Maybe the fact that native implementation will be used when available is  worth noting but I am not sure

> On the SecureStorage constructor let's omit the _use_sjcl flag and use an options dict instead, with {native: true} as default values. This allows more options to be added later, without breaking the constructor.

Implemented

> If possible it would be nice if the commits where you add/remove sjcl.js were squashed since they just add noise.

Commits squashed. If you wish I can squash the whole thing into one commit. (now that I know how to do it)

> Perhaps we should set a milestone where the sjcl would be removed and document it in the README

I believe that the time to drop the sjcl would be when API >= 21 will be very common.

**Comment by ggozad** [comment]
Merged and released. Thanks again.

**Comment by gcollazo** [comment]
🎉 Great improvement. Thanks for the great work.

**Pull request merged**
