### PR TITLE
feat: add keys and clear methods

### PR DESCRIPTION
**Pull request by yyfearth**
Implementation for iOS, Android, Windows and Browser is done, as well as tests and docs update.

For Windows, I do not have device and env setup for me to run the test, please help me to test it.
And please review my code, esp. the native implementation for iOS and Windows, since I never write ObjC code before, and never tried code for Win10 platform.

For JS, I write all my code in plain old ES3 ways for best compatibility.

This PR is mentioned in issue #64.

### CODE REVIEW

**Comment by ggozad** [comment]
Awesome! Thank you!
It will take me a while till I get to this since I am in between moving houses but will do so eventually :)

**Comment by yyfearth** [comment]
Hi @sgrebnov , since you have implemented the windows version, could you help me test my newly added code works or not?
I have included windows implementation with test script, but I do not have windows device or emulator to run the test.

**Comment by ggozad** [comment]
Your iOS implementation is just fine, I will look into the windows one this week what at the office.

**Comment by sgrebnov** [comment]
Adding @vladimir-kotikov to help w/ Windows test

**Comment by yyfearth** [comment]
@sgrebnov I have already implemented the windows version in src/windows/SecureStorage.js, and I think the api should be enough.
But I'm not sure if my code works or not since I do not have a Windows device with proper dev env setup.

**Comment by ggozad** [comment]
The windows has some problems, namely that exceptions are thrown when there are no credentials. Fixing these and updating tests, should be able to release today.

**Comment by ggozad** [comment]
Thanks all for the work, merged and released.

**Comment by yyfearth** [comment]
@ggozad You forgot to push a git tag for the  v2.6.0 for the releases.

**Comment by ggozad** [comment]
@yyfearth ops :)

**Pull request merged**
